"""add editable user profile name and avatar color

Revision ID: be76712242d1
Revises: da6b47f8cd61
Create Date: 2026-07-25 11:45:30.925126
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be76712242d1'
down_revision: str | None = 'da6b47f8cd61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_color')
    op.drop_column('users', 'custom_display_name')
    # ### end Alembic commands ###
