"""add chat history persistence columns and session uniqueness

Revision ID: f47667fd42f6
Revises: be76712242d1
Create Date: 2026-07-25 13:52:38.287519
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f47667fd42f6'
down_revision: str | None = 'be76712242d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('uncertainty', sa.Enum('low', 'medium', 'high', 'not_applicable', name='answer_uncertainty_level', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('chat_messages', sa.Column('active_index_version', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('retrieved_evidence_count', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_chat_sessions_repository_user', 'chat_sessions', ['repository_id', 'created_by_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_sessions_repository_user', 'chat_sessions', type_='unique')
    op.drop_column('chat_messages', 'retrieved_evidence_count')
    op.drop_column('chat_messages', 'active_index_version')
    op.drop_column('chat_messages', 'uncertainty')
    # ### end Alembic commands ###
